### ISSUE TITLE
web3 error during node server.js 

### ISSUE THREAD

**Issue by bl1pbl0p** [kylelobo/AuthentiFi#6]
Below is console log after node server.js command

C:\Users\User\Desktop\AuthentiFi>node server.js
Talking with a geth server 0.20.6

C:\Users\User\Desktop\AuthentiFi\node_modules\web3\lib\web3\httpprovider.js:101
    throw errors.InvalidResponse(request.responseText);
    ^

Error: Invalid JSON RPC response: undefined
    at Object.InvalidResponse (C:\Users\User\Desktop\AuthentiFi\node_modules\web3\lib\web3\errors.js:38:16)
    at HttpProvider.send (C:\Users\User\Desktop\AuthentiFi\node_modules\web3\lib\web3\httpprovider.js:101:18)
    at RequestManager.send (C:\Users\User\Desktop\AuthentiFi\node_modules\web3\lib\web3\requestmanager.js:58:32)
    at Eth.get [as coinbase] (C:\Users\User\Desktop\AuthentiFi\node_modules\web3\lib\web3\property.js:107:62)
    at Object.<anonymous> (C:\Users\User\Desktop\AuthentiFi\server.js:426:36)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)

**Comment by r-destron** [comment]
Why is this issue not resolved?

**Comment by itzhv14** [comment]
> Why is this issue not resolved?

🤷🏻‍♂️

**Comment by vijaykumar6520** [comment]
Hey Been trying to run this, stuck on the same Error message.. :-(  did anyone find any Fix ??

**Comment by Stacker7** [comment]
Did anyone finally find the issue? Could it be a version mismatch?

**Comment by itzhv14** [comment]
Nope 🥲
