### ISSUE TITLE
TypeError: web3.eth.contract is not a function

### ISSUE THREAD

**Issue by Rexdomine** [kylelobo/AuthentiFi#8]
when I run node server.js I get the error below please how can I solve it 

Talking with a geth server undefined 

/Volumes/Untitled/Conterfix/AuthentiFi/server.js:420
const contract = web3.eth.contract(abiArray);
                          ^

TypeError: web3.eth.contract is not a function
    at Object.<anonymous> (/Volumes/Untitled/Conterfix/AuthentiFi/server.js:420:27)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47

**Comment by MrAnayDongre** [comment]
Try using this : 
`MyContract = new web3.eth.Contract(abi)`

Check out the [Docs](https://web3js.readthedocs.io/en/1.0/web3-eth-contract.html#eth-contract)
When using version 1.0.x you need to pass in the Application Binary Interface, i.e. abi. And use the new keyword.
